# Generated by Django 6.0.7 on 2026-08-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
