# Generated by Django 6.0.7 on 2026-08-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='day_of_birth',
            field=models.SmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='month_of_birth',
            field=models.SmallIntegerField(blank=True, editable=False, null=True),
        ),
    ]
