# Generated by Django 6.0.7 on 2026-08-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_person_marital_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['month_of_birth', 'day_of_birth'], name='people_birthdate_idx'),
        ),
    ]
